title: Brendan Brundage
navbar_title: Brendan Brundage

author:
  name: Brendan Brundage # Your name
  bio:  Economics Ph.D. Candidate
  location: Fort Collins, Colorado
  avatar: "/_data/IMG_3222.png"
  email: "brendan.brundage@colostate.edu"

description: Ph.D. candidate in Economics at Colorado State University. Fort Collins, CO # description of your site

url: "https://brendanbrundage.github.io" # The base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # The subpath of your site, e.g. /blog

jekyllacademic:
  homepage_title: "About Me" # Your homepage title
  disqusname: # Your disqus sitename
  footer: Brendan Brundage, 2025 # Your name, Year
  contentlicense: "MIT" # Choose either one of these to put: MIT, Commons Clause, CC BY 4.0, CC BY-NC 4.0, CC BY-ND 4.0, CC BY-NC-ND 4.0, CC BY-NC-SA 4.0, CC BY-NC-SA 4.0, CC BY-SA 4.0
  socials:
    twitter: brendanbrundage # Your twitter username
    github: brendanbrundage # Your github username
    google scholar: Brendan Brundage 
    email: brendan.brundage@colostate.edu # Your email
 

# No need to edit this part, however if you want to, that's fine as well

permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

collections:
  pages:
    output: true
    permalink: /:name
  Teaching:
    output: true
    permalink: /:name
  Research:
    output: true
    permalink: /:name
  CV:
    output: true
    permalink: /:name

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
